### ISSUE TITLE
Support theme

### ISSUE THREAD

**Issue by pierluc-codes** [kyle-ilantzis/pl-sql-client#8]

**Comment by kyle-ilantzis** [comment]
Theme is now supported https://github.com/kyle-ilantzis/pl-sql-client/pull/21

We should now make a nice dark theme.

**Comment by kyle-ilantzis** [comment]
This https://github.com/kyle-ilantzis/pl-sql-client/pull/24 adds new nice themes.

We also need the ace editor to change theme, so that it matches the bootswatch theme, but for now it is fine.

Now we need the default theme to be selected in the app because now it is the first item in the list. This is important!
